[package]
name = "google_tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.29.14"
wgpu = "0.19.3"
pollster = "0.3.0"
bytemuck = { version = "1.14.3", features = [ "derive" ]}